# Site meta data
email: example@example.org
url: "http://example.org"


baseurl: "/"

plugins:
  - jekyll-polyglot

# not used by plugin but by liquid template
languages:          ['en']
default_lang: "en"
parallel_localization: true

language_data: data.lang.%%
language_includes_dir: _i18n

